<?php get_header(); ?>
  <?php get_template_part('template-parts/banner'); ?>
  <?php get_template_part('template-parts/solicitar-simulacao'); ?>
  <?php get_template_part('template-parts/barra-azul'); ?>
  <?php get_template_part('template-parts/products-veiculos','list'); ?>
  <?php get_template_part('template-parts/nossos-planos'); ?>
  <?php get_template_part('template-parts/metricas'); ?>
  <?php get_template_part('template-parts/entenda-consorcio'); ?>
  <?php get_template_part('template-parts/vantagens-consorcio'); ?>
  <?php get_template_part('template-parts/sobre-aglobo'); ?>
  <?php get_template_part('template-parts/ultimas-blog'); ?>
  <?php get_template_part('template-parts/opniao-clientes'); ?> 
  <?php get_template_part('template-parts/central-atendimento'); ?> 
  <?php get_template_part('template-parts/newsletter'); ?> 
<?php get_footer(); ?>